Universe     = vanilla
Priority     = 20

Notification = never
GetEnv       = true

Initialdir   = ./
Executable   = ./ListGenetate.csh
arguments = /star/u/szhu/pwg/pAu200_NetProtonFluctuation/StarAna/QA/RESULTS /star/u/szhu/pwg/pAu200_NetProtonFluctuation/StarAna/QA/list/ 6C1FAC49FA 20 $(item)

Log          = ./LogDir/run$(item).log
Output       = ./LogDir/run$(item).out
Error        = ./LogDir/run$(item).err
Queue item from seq 1 20 |